### ISSUE TITLE
待消化redux的一些理念后，我们就可以发布2.0了

### ISSUE THREAD

**Issue by hufeng** [QianmiOpen/iflux#9]
一直都想解决的一个问题就是不通过StoreMixin来通知Reat去re-render，但是StoreMixin还是太简单好用了。试着可以通过高阶函数来解决，这样可以更好的支持class-based的写法。

另外Store可以支持，reducer，这样就可以在保留单根数据源的基础上，可以做到很好地数据的分片。

**Comment by xiaoyong0312** [comment]
原来在这里mark 过！ 👍👍👍👍

**Comment by hufeng** [comment]
@xiaoyong0312 欢迎使用iflux2 :)  https://github.com/QianmiOpen/iflux2
